# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25d46f9626f2f9e3ad7dae0288c41917719e81a6f391d512be28a0894208a56a43e428baf74b3ddb5b1aea8b388b71f29d7305ae238d5d0917bad425ede386dc

test:
  secret_key_base: 8d90e80eb45bf86d505bb77d5bb6c06f5599cdd9a61253d4aa7f73cc2bb13fa1c74fc7f29036410747196b30349979dd6bba46bca5ca7e6f2594bfe64266a57f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
